### ISSUE TITLE
parameter declaration requries a type

### ISSUE THREAD

**Issue by maxandersen** [angelozerr/qute-ls#1]
this works:
```
{@java.util.List<java.lang.String> dependencies}
{#for dep in dependencies}
//DEPS {dep}
{/for}
```

but

```
{@java.util.List dependencies}
{#for dep in dependencies}
//DEPS {dep}
{/for}
```
does not. 

should assume it has java.lang.Object

**Comment by angelozerr** [comment]
Fixed with https://github.com/angelozerr/qute-ls/commit/443780b568895fd02bfc9a7dadaabafa057117f9

![image](https://user-images.githubusercontent.com/1932211/138647322-f6cf75f6-35ca-4f53-847e-d363f9b54cd5.png)

![image](https://user-images.githubusercontent.com/1932211/138647367-0d657193-0dcc-44b6-9b87-2c88caca0166.png)
