### ISSUE TITLE
Errors when editing JSON Qute templates

### ISSUE THREAD

**Issue by jeffmaury** [angelozerr/qute-ls#8]
Alizer (https://github.com/redhat-developer/alizer) is using Qute templates to render JSON output. When such template is edited, errors are generated but the content is valid.

![image](https://user-images.githubusercontent.com/695993/138848038-11779fae-7c1a-4d73-a98b-bf46675a4747.png)

**Comment by angelozerr** [comment]
I fixed error with parser expression:

![image](https://user-images.githubusercontent.com/1932211/138957820-8483bb77-7331-4389-8d85-191110739032.png)

The error which exists again are:

 * name(for result.name) which should be fixed with https://github.com/angelozerr/qute-ls/issues/9
 * the JSON error coming from JSON LS (I cannot do anything).
